### PR TITLE
Use text wrapping for error dialogs

### LINKED ISSUE #64: Error message not formatted correctly
**Describe the bug**
I used the latest branch `feature/open-file-dialog` and ran into a Github rate limit issue. The error message was not correctly displayed because the formatting was off. I hope the Github error itself is just a bug or maybe I was hitting the actual rate limit. 

Bildschirmfoto 2020-11-12 um 14 18 39

**Environment information:**

- OS: e.g. Mac OS

**Steps to Reproduce**
Not sure how to properly reproduce it as the issue requires a fairly long error message. One option would be to actually exhaust the request limit artificially and then use Skyimager. 

**Actual behavior**
Error message is displayed incorrectly.

### PR DESCRIPTION
**Pull request by i-hate-nicknames**
Fixes #64

Changes:
- Wrap lines of error text.

Does this change need to mentioned in CHANGELOG.md?

No

There is no way to specify when the line should be wrapped in characters, and label widget relies on parent width, so error dialogs now have fixed width.

### CODE REVIEW

File: pkg/imager/widgets/dialogs.go [hunk 1]
```diff
@@ -159,10 +167,17 @@ func ShowCustom(title, dismiss string, content fyne.CanvasObject, parent fyne.Wi
...
-
 	d.Show()
 }
 
+// ShowError displays an error dialog with a single OK button, that displays given text
+// The text is word wrapped
+func ShowError(text string, parent fyne.Window) {
+	label := widget.NewLabelWithStyle(text, fyne.TextAlignLeading, fyne.TextStyle{})
+	label.Wrapping = fyne.TextWrapWord
+	ShowCustom("Error blyat", "Ok", label, parent)
```
Comment (jdknives) [inline pkg/imager/widgets/dialogs.go]: Not sure we should add easter eggs to the Skyimager. Otherwise this works as expected and is cleaner than the previous PR. Good job.

Comment (i-hate-nicknames) [reply pkg/imager/widgets/dialogs.go]: Thanks, that indeed is not a correct spelling. Fixed.
