### PR TITLE
Fix/network connection errors

### LINKED ISSUE #18: skyimager-gui: multiple error types during no network condition
I've produced two errors:

1. Get https:api.github.com/repos/SkycoinProject/skybian/releases: dial tcp: lookup api.github.com: no such host
2. context deadline exceeded

When _we_ read these we have an idea of the problem and know where to look. 

But if I didn't know any better: the first one implies that the host doesn't exist; the second one is a fancy timeout.

**Environment information:**

- Windows10 Pro, version 1809
- macOS High Sierra, 10.13.6; Darwin 17.7.0

**Steps to Reproduce**

- For error#1: **First** disable or unplug network adapter _then_ run `skyimager-gui`
- For error#2: (with a working network connection) run `skyimager-gui`; press "Next"; _then_ disable or unplug network adapter; press "Previous"; press "Next"

**Possible implementation**
Maybe suggest to the user that they should first check their network connection (or test it for them)?

The direct link to the releases is a huge feature, well done!

### PR DESCRIPTION
**Pull request by i-hate-nicknames**
Fixes #18 

Changes:
- Add better error handling and reporting for networking errors

Does this change need to mentioned in CHANGELOG.md?

No

### CODE REVIEW

File: pkg/imager/latest_release.go [hunk 1]
```diff
@@ -95,11 +97,25 @@ func releaseStrings(releases []Release) (rs []string) {
 	return rs
 }
 
+// ErrNetworkConn is returned when it's impossible to make a request do to the network failure
```
Comment (jdknives) [inline pkg/imager/latest_release.go]: "due to network failure"

**Review by jdknives — CHANGES_REQUESTED** [review]
Good work overall. Please just change comment and investigate the Travis errors before merging.

File: pkg/imager/fyne.go [hunk 2]
```diff
@@ -93,7 +93,13 @@ func (fg *FyneUI) listBaseImgs() ([]string, string) {
 	d.Hide()
 
 	if err != nil {
-		dialog.ShowError(err, fg.w)
+		var message string
+		if errors.Is(err, ErrNetworkConn) {
+			message = "Network connection error"
```
Comment (jdknives) [inline pkg/imager/fyne.go]: We might also return something like: 

`Network connection error. Please ensure that you are connected to the internet correctly.`

**Review by jdknives — APPROVED** [review]
